services:
  # Command server (submission) - starts first and stays running
  submission:
    build:
      context: ${SUBMISSION_FOLDER:-./submission}
      dockerfile: Dockerfile
    container_name: submission_server
    volumes:
      - shared_pipes:/shared
    # Keep the container running and restart if it fails
    restart: unless-stopped
    # Add some debug output
    environment:
      - PYTHONUNBUFFERED=1
    # Health check to ensure the server is ready
    healthcheck:
      test: ["CMD", "test", "-p", "/shared/command_pipe", "-a", "-p", "/shared/response_pipe"]
      interval: 2s
      timeout: 1s
      retries: 30
      start_period: 5s
    networks:
      - isolated_network

  # Agent controller - runs the test commands and then exits
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    image: binance-agent-reasoning-v8:latest
    container_name: agent_controller
    volumes:
      - shared_pipes:/shared
      - ${SUBMISSION_FOLDER:-./submission}/PROMPT.json:/app/PROMPT.json:ro
      - ${SUBMISSION_FOLDER:-./submission}/DESCRIPTION.md:/app/DESCRIPTION.md:ro
    depends_on:
      submission:
        condition: service_healthy
    # Agent should exit after completing its work
    restart: "no"
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # Optional provider overrides
      - PROVIDER=${PROVIDER}
      - PROVIDER_AGENT=${PROVIDER_AGENT}
      - PROVIDER_VALIDATE=${PROVIDER_VALIDATE}
      - PROVIDER_EVAL=${PROVIDER_EVAL}
      - FORCE_EVAL_FINALIZE=${FORCE_EVAL_FINALIZE}
      - ANTHROPIC_MAX_TOKENS=${ANTHROPIC_MAX_TOKENS}
      # Optional manual guidance and failure handling
      - HINT_ON_FAILURE=${HINT_ON_FAILURE}
      - MAX_TOOL_FAILURES_BEFORE_HINT=${MAX_TOOL_FAILURES_BEFORE_HINT}
      - AGENT_HINT=${AGENT_HINT}
      - AGENT_HINT_FILE=${AGENT_HINT_FILE}
      - EVAL_HINT=${EVAL_HINT}
      - EVAL_HINT_FILE=${EVAL_HINT_FILE}
      # Fallback model for evaluator/validator when provider errors
      - OPENAI_FALLBACK_MODEL=${OPENAI_FALLBACK_MODEL}
      - OPENAI_VALIDATE_MODEL=${OPENAI_VALIDATE_MODEL}
      - OPENAI_EVAL_MODEL=${OPENAI_EVAL_MODEL}
      # Unified experiment metadata
      - UNIFIED_MODEL=${UNIFIED_MODEL:-unknown}
      - UNIFIED_REASONING=${UNIFIED_REASONING:-unknown}
      - UNIFIED_IMPLEMENTATION=${UNIFIED_IMPLEMENTATION:-Binance Framework}
      - UNIFIED_EXPERIMENT_ID=${UNIFIED_EXPERIMENT_ID:-unknown}
      - UNIFIED_MAX_STEPS=${UNIFIED_MAX_STEPS:-30}
    # Agent has access to both networks for communication
    networks:
      - default
      - isolated_network

volumes:
  # Shared volume for named pipes communication
  shared_pipes:
    driver: local

networks:
  # Internal network with no external internet access
  isolated_network:
    driver: bridge
    internal: true
